<script setup lang="ts">
useHead({ title: 'About Willcoll Agencies | Business Advisory Firm, Nairobi', meta: [{ name: 'description', content: 'Learn about Willcoll Agencies mission, values, and approach to advisory for growing Kenyan organizations.' }] })
const values = [
  ['Integrity', 'We give the advice a client needs to hear, not only what is easiest to say.'],
  ['Rigor', 'Every engagement follows a disciplined, evidence-based methodology.'],
  ['Accessibility', 'Enterprise-grade advisory should not require an enterprise budget.'],
  ['Partnership', 'We measure success by our clients outcomes, not billable hours.']
]
const approach = ['Diagnose — We start by understanding the actual business problem, not the assumed solution.', 'Design — We build a scoped, practical plan matched to your organization’s size and constraints.', 'Deliver — Our team executes alongside yours, with clear milestones and accountability.', 'Sustain — We hand over frameworks and capability your team can maintain independently.']
</script>
<template>
  <div>
    <SharedPageHero eyebrow="About Willcoll" title="Advisory for organizations ready to grow with confidence." subtitle="We bring senior-level thinking, practical delivery, and Kenyan market fluency to the decisions that shape your organization." />
    <section class="py-16 lg:py-24 bg-white"><div class="max-w-7xl mx-auto px-6 lg:px-10 grid lg:grid-cols-12 gap-12 items-start"><div class="lg:col-span-5"><p class="text-orange-600 text-xs font-bold uppercase tracking-widest mb-4">Our story</p><h2 class="text-3xl lg:text-4xl leading-tight">Built to close a real gap in the market.</h2></div><div class="lg:col-span-6 lg:col-start-7 text-lg text-gray-600 leading-relaxed space-y-5"><p>Willcoll Agencies was founded on a simple observation: Kenyan businesses that are past the informal, founder-managed stage still struggle to access advisory support that matches their ambition.</p><p>Enterprise consulting firms are built for enterprise budgets and timelines. Willcoll was built to close that gap — bringing rigorous, senior-level business advisory to SMEs, family businesses, NGOs, SACCOs, and growing corporates across Kenya.</p></div></div></section>
    <section class="bg-ink-900 py-16 lg:py-24 text-white"><div class="max-w-7xl mx-auto px-6 lg:px-10 grid md:grid-cols-2 gap-8"><div class="border border-white/15 rounded-2xl p-8"><p class="text-orange-400 text-xs font-bold uppercase tracking-widest mb-4">Our mission</p><p class="font-heading text-2xl leading-relaxed">To equip growing Kenyan organizations with the compliance, risk management, and strategic advisory capability they need to operate with confidence and scale sustainably.</p></div><div class="border border-white/15 rounded-2xl p-8"><p class="text-orange-400 text-xs font-bold uppercase tracking-widest mb-4">Our vision</p><p class="font-heading text-2xl leading-relaxed">To be the most trusted business advisory partner for Kenya’s growing and mid-market organizations.</p></div></div></section>
    <section class="py-16 lg:py-24 bg-gray-50"><div class="max-w-7xl mx-auto px-6 lg:px-10"><SharedSectionHeading eyebrow="What guides us" title="Our values show up in the work." centered /><div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-5 mt-12"><div v-for="([name, text], i) in values" :key="name" class="bg-white border border-gray-100 rounded-2xl p-6"><span class="text-orange-500 font-mono text-sm">0{{ i + 1 }}</span><h3 class="text-xl mt-5 mb-3">{{ name }}</h3><p class="text-sm text-gray-600">{{ text }}</p></div></div></div></section>
    <section class="py-16 lg:py-24 bg-white"><div class="max-w-7xl mx-auto px-6 lg:px-10 grid lg:grid-cols-2 gap-12"><div class="rounded-3xl bg-orange-100 p-8 lg:p-12"><p class="text-orange-600 text-xs font-bold uppercase tracking-widest mb-5">Leadership</p><div class="w-16 h-16 rounded-2xl bg-orange-500 text-white flex items-center justify-center font-heading text-3xl mb-7">WK</div><h2 class="text-3xl mb-1">Wilson Kimani</h2><p class="text-orange-600 font-semibold mb-5">Managing Partner</p><p class="text-gray-700">Wilson leads Willcoll Agencies’ advisory practice, working directly with clients across compliance, governance, risk, and transformation engagements.</p></div><div><p class="text-orange-600 text-xs font-bold uppercase tracking-widest mb-4">How we work</p><h2 class="text-3xl mb-7">Structured enough to be rigorous. Practical enough to deliver.</h2><ol class="space-y-5"><li v-for="(step, i) in approach" :key="step" class="flex gap-5 border-b border-gray-100 pb-5"><span class="text-orange-500 font-mono font-bold">0{{ i + 1 }}</span><p class="text-gray-600">{{ step }}</p></li></ol></div></div></section>
  </div>
</template>
